variable "allocated_storage" {}
variable "db_name" {}
variable "engine" {}
variable "engine_version" {}
variable "publicly_accessible" {}
variable "multi_az" {}
variable "instance_class" {}
variable "username" {}
variable "password" {}
variable "parameter_group_name" {}
variable "skip_final_snapshot" {}
variable "subnet_group_name" {}
variable "subnet_group_ids" {}
variable "vpc_security_group_ids" {}
variable "backup_retention_period" {}
variable "backup_window" {}
